### ISSUE TITLE
Kibana 5.0.1 will not start

### ISSUE THREAD

**Issue by NirBY** [Top-Q/difido-reports#114]
Using difido-reports v2.0.04 & 2.0.05-ALPHA.
There error getting in the log - "This version of Kibana requires Elasticsearch v5.0.1 on all nodes. I found the following incompatible nodes in your cluster: v2.3.1 "

What ver of Kibana should I use?
Please also add it to Wiki.

**_Getting en error when starting it (from the log)_**:
  log   [18:15:59.936] [info][status][plugin:kibana@5.0.1] Status changed from uninitialized to green - Ready
  log   [18:16:00.160] [info][status][plugin:elasticsearch@5.0.1] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [18:16:00.338] [info][status][plugin:console@5.0.1] Status changed from uninitialized to green - Ready
  log   [18:16:01.335] [info][status][plugin:timelion@5.0.1] Status changed from uninitialized to green - Ready
  log   [18:16:01.389] [info][listening] Server running at http://localhost:5601
  log   [18:16:01.393] [info][status][ui settings] Status changed from uninitialized to yellow - Elasticsearch plugin is yellow
  log   [18:16:01.431] [error][status][plugin:elasticsearch@5.0.1] **Status changed from yellow to red - This version of Kibana requires Elasticsearch v5.0.1 on all nodes. I found the following incompatible nodes in your cluster: v2.3.1 @ 127.0.0.1:9200 (0.0.0.0)**
  log   [18:16:01.433] [error][status][ui settings] Status changed from yellow to red - Elasticsearch plugin is red

**Comment by itaiag** [comment]
Since the ELK stack is not keeping backward compatibility, and we are not updating the embedded Elastic every time a new version is released, you should use the previous version of Kibana. 
Version 4.5.0 should be work just fine.

**Comment by itay85** [comment]
What if I use external elastic , this mean I can update kibana ? 
does Difido works well with updated elastic version ?

**Comment by itaiag** [comment]
In the Difido we are using the Java API of Elastic. Sometimes they break backward compatibility and sometimes they don't.
