### ISSUE TITLE
After Upgrading From V2.0.1 to V2.1.0 Getting Error - Failed to connect to Elasticsearch

### ISSUE THREAD

**Issue by NirBY** [Top-Q/difido-reports#126]
Attached is log.
[difido.txt](https://github.com/Top-Q/difido-reports/files/900110/difido.txt)

**Comment by NirBY** [comment]
The real issue here is - I am missing "org.elasticsearch.*" log prints for troubleshooting the issue.
And it seems that configuration changes done did not take place (#113).

**Comment by NirBY** [comment]
OK. now I saw it..
Please add it to wiki.
"
This Elastic version can not be executed while embedded in the server and it requires an external installation.
"

**Comment by itaiag** [comment]
Glad you figured it out. 

Thanks for the suggestion but It is already mentioned is the getting [started guide](https://github.com/Top-Q/difido-reports/wiki/Getting-Started) and in the release notes.
