### ISSUE TITLE
TestNG binder - tests should fail if there was a report with "failure" status

### ISSUE THREAD

**Issue by ronyb** [Top-Q/difido-reports#136]
If `report.log("some message", Status.failure)` was invoked during the test, the TestNG test should continue execution, but it should end with a failure status.

We'll use TestNG's `SoftAssert` to implement this.

**Comment by itaiag** [comment]
Duplicate with #137

**Comment by itaiag** [comment]
The current implementation causes the teardown phase to be skipped. There is a need for another solution. Rolling back and reopening the issue.
