### ISSUE TITLE
Setup phase should be added to any report before test context

### ISSUE THREAD

**Issue by ZahiZilberman** [Top-Q/difido-reports#138]
Currently, any reported message before an actual test has started, will be discarded. Instead, a special node should be created as "Setup" until a test context is created

**Comment by itaiag** [comment]
One option is to add to the **ReportManagerHook** the **IInvokedMethodListener** listener. This will allow reporters to get notified before and after each configuration and test method.

The events method signatures are:

```java
	@Override
	public void beforeInvocation(IInvokedMethod method, ITestResult testResult) {
	}

	@Override
	public void afterInvocation(IInvokedMethod method, ITestResult testResult) {
		
	}

```
It is also easy enough to know if the method is before or after method by calling the `method.getTestMethod().isBeforeMethodConfiguration()` call.

The reporters will collect all the report messages that are logged in the setup phase and will add them to the test body when the test starts. 

The only problem that I currently see is that there is probably no way to get the name of the test method that the configuration method is linked to. That means that if an exception is thrown in the setup phase and we would like to report the exception we don't know what is the name of the test to create in the report.
