### ISSUE TITLE
problem with screenshot in @BeforeClass method

### ISSUE THREAD

**Issue by idanharari** [Top-Q/difido-reports#147]
There is a problem with the following scenario:
**class1**
      
1. @test  test1 ...

**class2** 
    

1. @beforeClass-..... takeSceenshot(){
         File scrFile = driver.getScreenshotAs(OutputType.FILE);
         report.addImage(scrFile, screenshotDescription);
.....
2.  @test test2 ...

the screenshot saved in  ...\current\tests\test-1 and not in ...\current\tests\test-2
Thus the execution tree of test2 looks like this  (in setup):
![test2](https://user-images.githubusercontent.com/23376375/28754483-a98d5706-754e-11e7-8e74-8633af48d171.png)
What can I do to fix this? 
thanks

**Comment by itaiag** [comment]
What Difido version are you using?

**Comment by idanharari** [comment]
2.1.00 with TestNG Binder

<groupId> il.co.topq.difido </groupId>
            <artifactId> difido-testng </artifactId>
            <version> LATEST </version>

**Comment by itaiag** [comment]
The support for fixture methods in TestNG was introduced only last Saturday. Can you check the behavior with version **2.1.01-SNAPSHOT** ?

**Comment by idanharari** [comment]
Still the same problem. 
The Screenshots from the Setup (before class) are saved in the previous test folder.

**Comment by Ben-Mark** [comment]
Are the screenshots from the @AfterClass method saved in the correct folder?
