### ISSUE TITLE
Execution Tree view - top level icon is always JSystem

### ISSUE THREAD

**Issue by ronyb** [Top-Q/difido-reports#165]
When viewing reports in "Execution Tree" view, the top level icon says "JSystem" even though the tests were executed by TestNG or any other framework.

Need to change the icon to match the testing framework, or something generic which will fit all kinds of test frameworks.

![execution_tree_jsystem](https://user-images.githubusercontent.com/4738896/30538373-66a6a3a8-9c76-11e7-97bf-95e392b4ce9e.PNG)

**Comment by itaiag** [comment]
Adding the correct icon for each framework is a bit overkill. I think we can just lose or change the label and replace the icon.

**Comment by ronyb** [comment]
Done & and merged to master
