### ISSUE TITLE
Supporting of Cyrillic fonts

### ISSUE THREAD

**Issue by iSvyat** [Top-Q/difido-reports#166]
Difido report does not support cyrillic. Can you add support of UTF-8 format or something else to see the cyrillic chars? Or may be I simply dont know how to turn on this opportunity.

![image](https://user-images.githubusercontent.com/25739126/30731319-6a1ed544-9f75-11e7-9e31-06b5f183458b.png)

**Comment by itaiag** [comment]
Hi.

Please provide the binder that you are using (NUnit, TestNG, JSystem), and the Difido version.

**Comment by iSvyat** [comment]
JSystem, in the runtime reporter all is ok. JSystem version 6.1.05. Cant sau what version of the Difido reporter associated with it.

**Comment by iSvyat** [comment]
Is it possible to solve it? Could you answer please?

**Comment by itaiag** [comment]
The Difido reports and JSystem are using UTF-8 by default, so I am not sure why you can't see Cyrilic fonts. 
I tried to reproduce it with the following test:

```Java
	@Test
	public void testCyrillic() throws Exception {
		report.step("About to print cyrillic text");
		report.report("ЗАПИСЬ!!!");
	}
```

And I got the following report

![screenshot from 2017-10-08 13-05-49](https://user-images.githubusercontent.com/1835335/31315852-893f970e-ac29-11e7-8686-945dbce204ef.png)

If you still see the problem, please provide more detailed steps that will allow me to reproduce the problem.

**Comment by iSvyat** [comment]
It is really strange, I still see an issue. JSystem shows correctly

![image](https://user-images.githubusercontent.com/25739126/31379014-bf55b552-adb5-11e7-949e-36d5fb8b4837.png)
but Difido shows 

![image](https://user-images.githubusercontent.com/25739126/31379087-008f8174-adb6-11e7-949a-182a461a8068.png)

I have found, that this specific character � is usually the sign of an invalid (non-UTF-8) character showing up in an output (like a page) that has been declared to be UTF-8. But cyrillic is UTF-8.. I dont know what happens) I tried with different browsers, but it did not help.

**Comment by itaiag** [comment]
I tried it with JSystem 6.1.05, Chrome and Firefox and still could not reproduce the problem. 
I am keeping the issue open for now in hope that I will be able to reproduce it sometime (or better yet, it will miraculously start working on your environment :)).

**Comment by iSvyat** [comment]
Big thanks, I will try to find out what`s going wrong in my environment.

**Comment by iSvyat** [comment]
Interesting moment, it seems there are problems with .js files, which were generated for reports. When I decode them manually via notepad++ into UTF-8 without BOM, reports are showing normally without question marks in a black diamond.

**Comment by iSvyat** [comment]
Can you tell the setup which you used, where problem is not reproducible? Maybe  OS, IDE are important. I am using WIndows 10 with Eclipse, but JSystem continues to save .js files in non-itf-8.

**Comment by iSvyat** [comment]
Thanks for the fix Itai. When do you plan to add new difido version to the JSystem project?
