### ISSUE TITLE
Error: maven.top-q.co.il 

### ISSUE THREAD

**Issue by avrahamShutterFly** [Top-Q/difido-reports#168]
Environment:
Mac, testNG.
Clone the project and Run from terminal, And I got this error 
BUILLD FAILURE
Failed to execute goal on project tests: Could not resolve dependencies for project shutterfly.automation:tests:jar:0.0.1-SNAPSHOT: Failure to find shutterfly.automation:infra:jar:0.0.1-SNAPSHOT in http://maven.top-q.co.il/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of topq has elapsed or updates are forced

**Comment by itaiag** [comment]
The Shutterfly infra project is part of your automation project and it is not related to the Difido project.
