### ISSUE TITLE
can't get link to difido job description  (after updating the new server version )

### ISSUE THREAD

**Issue by barakshr** [Top-Q/difido-reports#186]
In our Jenkins CI job we are using the groovy command:
**def linkString = json.find { it.Description == desc }?.Link**
we suspect that the result is empty

Example for adding-report-link
https://github.com/Top-Q/difido-reports/wiki/Server-API#example-for-adding-report-link-in-jenkins

**Comment by barakshr** [comment]
follow up , iddan found that the following change will find the link:
**def linkString = json.find{it[1] == desc}[2]**

**Comment by itaiag** [comment]
The data structure that returns when calling the reports API was changed for issue #158. This was done to allow the data table plugin to perform auto refresh. 
This is the same call that is done when displaying the execution results in the main Difido server view, so you can use Chrome developer tool or any other sniffing tool to see the exact data that returned from the server.
