### ISSUE TITLE
server.address define at start file to 0.0.0.0 --> Elastic show URL 0.0.0.0 .....

### ISSUE THREAD

**Issue by igivon** [Top-Q/difido-reports#191]
spring server.address is define at start file to default of 0.0.0.0
this configuration cause elastic Url to show 0.0.0.0 and not the correct ip.

![image](https://user-images.githubusercontent.com/7386112/37563534-8fad6040-2a8b-11e8-8f5a-75154e368ceb.png)
 
- need to add this configuration to the wiki or take it out to the difido configuration file

# **configuration taken from Start.sh:
```
#=====================**==================
#      SPRING BOOT CONFIGURATION
#=======================================

# The port to use
readonly PORT=8080

readonly HOST=0.0.0.0

# Log levels: TRACE, DEBUG, INFO, WARN, ERROR
readonly LOGGING_LEVEL=ERROR

```
# **ESController.java findTestURL method:**
```
 private String findTestUrl(ExecutionMetadata executionMetadata, String uid) {
		if (executionMetadata == null) {
			return "";
		}
		// @formatter:off
		// http://localhost:8080/reports/execution_2015_04_15__21_14_29_767/tests/test_8691429121669-2/test.html
		return "http://" + System.getProperty("server.address") + ":" + System.getProperty("server.port") + "/"
				+ Common.REPORTS_FOLDER_NAME + "/" + executionMetadata.getFolderName() + "/" + "tests" + "/" + "test_"
				+ uid + "/" + "test.html";
		// @formatter:on
	}
```

**Comment by itaiag** [comment]
The idea is that you could edit the *start.sh* or *start.bat* with the correct IP of the server. This can not done automatically (or, I didn't figured out a good way to do it).
