### ISSUE TITLE
execution.properties not working while using the api

### ISSUE THREAD

**Issue by orbenda1905** [Top-Q/difido-reports#192]
Hi,

I'm creating an execution through the API and I need to add some execution.properties in order to filter in the Kibana. (I'm using the JSystem's script - runScenario.bat)
I did it as it says on the wiki and it doesn't work.
While debugging, I noticed that the properties shows in the ExecutionMetaData but not in the scenario properties like it should be.
When I use JSystem's GUI and edit the remoteDifido.properties file with the execution.properties it works fine (it shows on the scenario properties map while debugging).

Thanks

**Comment by itaiag** [comment]
The execution properties and the scenario properties are actually not exactly the same thing. The execution properties are added as additional columns in the execution list in the main server view while the scenario properties are added to the HTML report in the overview page and are also copied to the Elastic search entities. 
The reason that you see the execution properties as scenario properties when running from JSystem or any other framework is that the binder is responsible for adding the execution properties as scenario properties. 
When You are creating the execution using the API, you are bypassing the binder mechanism so the execution properties are not included in the scenario properties.

**Comment by itaiag** [comment]
Since this is a requirement that I get from many users, I am considering performing the scenario properties update in the server side instead in each one of the binders.
