### ISSUE TITLE
Only if single test is run the report generated has two test instances

### ISSUE THREAD

**Issue by muzammilk** [Top-Q/difido-reports#212]
I am using difido with testng and when I run my tests I see an additional test result for all the tests in the report. 

For example -
In the IDE console I see the following as testng results on running a single test-
**Default suite
Total tests run: 1, Failures: 1, Skips: 0** 

However in the html report generated shows two test results even if a single test is executed (additional one is always a pass). Below are the screenshots of the report.

![image](https://user-images.githubusercontent.com/36081261/50699142-fbb76000-1014-11e9-80bf-2eeb7874828b.png)
![image](https://user-images.githubusercontent.com/36081261/50699218-3b7e4780-1015-11e9-8ae0-385b9d6e7d0f.png)
![image](https://user-images.githubusercontent.com/36081261/50699224-446f1900-1015-11e9-8206-ca2fea9f2827.png)

**Comment by itaiag** [comment]
Which Eclipse version are you using? There is a bug in two of the versions with the integration with the TestNG library. From some reason it publishes the test events twice.

Try to run the tests directly from Maven and see if the report works as expected. If it is, try to update your Eclipse version to the latest one.
