### ISSUE TITLE
Exception in thread "I/O dispatcher 1" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by NirBY** [Top-Q/difido-reports#242]
Thank you for this wonderful app!
It works great, but unfortunately after ~90 days of running 2-3K test cases per day, is got java.lang.OutOfMemoryError: Java heap space.
If you need additional data please update.

**System Info**:
Difido Ver: v2.2.05
Elasticsearch ver: v6.7.0
Configuration used:[difido_config.txt](https://github.com/Top-Q/difido-reports/files/4977199/difido_config.txt)

**Adding full log**:
[difido.log](https://github.com/Top-Q/difido-reports/files/4977192/difido.log)

**Supervisor config used**: 
```
[program:Difido-Server] 
command=sudo /usr/bin/java -Xms256m -Xmx1024m -XX:MaxDirectMemorySize=512M -Dserver.address=192.168.50.10 -Dserver.port=8088 -Dlogging.level.org.springframework.web=ERROR -Dlogging.level.il.co.topq.report=DEBUG -cp "lib/difido-server.jar:plugin/*" org.springframework.boot.loader.JarLauncher
directory=/usr/local/bin/difido-server
process_name=Difido_Server
autostart=true
autorestart=true
startsecs=30
startretries=3
priority=110
stopwaitsecs=30
user=root
stdout_logfile=/usr/local/bin/difido-server/log/difido.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=10
redirect_stderr=true 
stopsignal=INT
```

**Comment by itaiag** [comment]
I'm working on a new version with much less memory consumption. It is due to be released soon

**Comment by NirBY** [comment]
Workaround it using: 
`-XX:OnOutOfMemoryError="/usr/bin/supervisorctl restart Difido-Server:Difido_Server"`
[supervisord config used](https://github.com/Top-Q/difido-reports/files/6280505/supervisord.conf.txt)
