### ISSUE TITLE
Built-in elastic search server doesn't start (2.3.00)

### ISSUE THREAD

**Issue by ValorHeart** [Top-Q/difido-reports#244]
Following the Guide from Difido Wiki: https://github.com/Top-Q/difido-reports/wiki/ElasticSearch-and-Kibana

After making sure that 'elastic.enabled=false' in the 'difido_config.properties' file,
When starting the Difido-Server, there is no such evidence of Elastic search service to be operated.
I have checked it by two ways:
1. http://localhost:9200
2. Look at the Difido logs file and found this error: **2020-07-26 17:56:20.825  WARN 641 --- [pool-5-thread-1] i.c.t.r.business.elastic.ESController    : Elasticsearch server is down**

Attached the full log file
[difido.log](https://github.com/Top-Q/difido-reports/files/4977845/difido.log)

**Comment by itaiag** [comment]
It is no longer possible to embed Elastic in other Java applications. The documentation was not up to date.
