### ISSUE TITLE
add an ability to set execution description dynamically 

### ISSUE THREAD

**Issue by itay85** [Top-Q/difido-reports#95]
It will be extremely helpful if we can set the execution description value according to the build version
or scenario name and not manually set it up for every run , this maybe more of jsystem issue

**Comment by itaiag** [comment]
This can be done from the **execution.description** key in the **remoteDifido.properties** file that is located at the root of the project.

**Comment by itaiag** [comment]
For more information on the **remoteDifido.properties**, take a look at [this ](https://github.com/Top-Q/difido-reports/wiki/Remote-Difido-Properties-Explained)Wiki page
