### ISSUE TITLE
questions on a CI flow with the difido report server

### ISSUE THREAD

**Issue by YoavLevinger** [Top-Q/difido-reports#98]
Nice report server indeed !

When using jenkins to run the JSystem scenarios, each job is running its own test suite/scenario and several of which are eventually a part of a larger suite, such as: acceptance, regression, E2E, etc. the difido server is a great tool to aggregate all of these. 

Yet, there are several issues that are still open and you might be able to assist:

- How can I pass the report parameters in the maven command, instead of creating a file for each test execution (this is the workaround for now). 

For example:
mvn clean install org.jsystemtest:jsystem-maven-plugin:run -Dscenario=scenarios/<scenario_name> -Dsut=<mySUT>.xml -Dport=8585 -Dexecution.description=<test_description> -Dappend.to.existing.execution=true -Dexisting.execution.id=-1 -Dforce.new.execution=false -Denabled=true -Dexecution.properties=version=6.8.5.6;build=1234;user=Mocky2 -Dhost=10.10.10.10 -Duse.shared.execution=true

- How can I control the list of email recipients for each report ?

- How can I extend the mail report for additional parameters, such as the $meta.build, $meta.version etc. ? (The $meta.description & $meta.id both works well) 

- How I can set the mail subject ?
- How can I add to the mail body selected sections of the report/test results ?

**Comment by itaiag** [comment]
Hi.

Execution properties are suited for most cases, so you can add them at run time. The specific method of adding them is depended on the binder that you are using. For example, if you are using the JSystem binder, use this example for adding execution properties (It is called *run properties* in JSystem)

~~~~ Java
	@Test
	@TestProperties(name = "Test that adds run properties")
	public void testAddRunProperties() {
		report.setContainerProperties(0, "Version", "1.02.3-RC");
		report.setContainerProperties(0, "Build", "46");
		report.setContainerProperties(0, "User", "Itai");
		report.setContainerProperties(0, "Operating System", System.getProperty("os.name"));
		report.setContainerProperties(0, "Java Runtime", System.getProperty("java.runtime.name"));
		report.setContainerProperties(0, "Java Version", System.getProperty("java.runtime.version"));
	}

~~~~

Regarding customizing the mail. for the level of customization you are describing, you will need to implement your own mail plugin. For information of how to do it please refer to the [Wiki page](https://github.com/Top-Q/difido-reports/wiki/Developing-Plugins). You can also take a look at [this](https://github.com/Top-Q/difido-trends-mail-plugin) example.

**Comment by NirBY** [comment]
Will it be fixed? 
(Passing parameters in execution, instead of changing "remoteDifido.properties" each run)
